language: erlang
otp_release:
  - 17.1
  - 17.0
  - R16B03-1
  - R16B
  - R15B03
  - R15B02
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02
script: "make rebuild"
branches:
  only:
    - master
    - feature_publisher
